import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  systemSidebar: [
    'intro',
    'market-research',
    {
      type: 'category',
      label: 'System Blueprint',
      collapsed: false,
      items: [
        'system/george',
        'system/api',
        'system/ingest-flow',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'operations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Retrospectives',
      items: [
        {
          type: 'autogenerated',
          dirName: 'retrospectives',
        },
      ],
    },
    {
      type: 'category',
      label: 'The Lab',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'lab',
        },
      ],
    },
  ],
  projectsSidebar: [
    {
      type: 'category',
      label: 'Active Projects',
      collapsed: false,
      items: [
        'projects/s2p',
        'projects/studio-c',
        'projects/cptv',
        'projects/tuthill',
      ],
    },
  ],
};

export default sidebars;
